export const ADD_PATIENT_DETAILS = "ADD_PATIENT_DETAILS";
export const REMOVE_PATIENT_DETAILS = "REMOVE_PATIENT_DETAILS";
export const ADD_PATIENT_DIAGNOSIS = "ADD_PATIENT_DIAGNOSIS";
export const REMOVE_PATIENT_DIAGNOSIS = "REMOVE_PATIENT_DIAGNOSIS";
export const ADD_DIAGNOSIS_NUMBER = "ADD_DIAGNOSIS_NUMBER";
export const REMOVE_DIAGNOSIS_NUMBER = "REMOVE_DIAGNOSIS_NUMBER";

export const SAVE_ALL_ALLERGENS = "SAVE_ALL_ALLERGENS";

export const SAVE_ALL_PROTOCOLS = "SAVE_ALL_PROTOCOLS";