export const ADD_NEW_PATIENT_DETAILS = "ADD_NEW_PATIENT_DETAILS";
export const ADD_NEW_PATIENT_DIAGNOSIS = "ADD_NEW_PATIENT_DIAGNOSIS";
export const ADD_NEW_DIAGNOSIS_NUMBER = "ADD_NEW_DIAGNOSIS_NUMBER";


export const SAVE_ALL_ALLERGENS = "SAVE_ALL_ALLERGENS";
export const SAVE_ALL_PROTOCOLS = "SAVE_ALL_PROTOCOLS";


export const REMOVE_DIAGNOSIS_NUMBER = "REMOVE_DIAGNOSIS_NUMBER";


export const ADD_DEMO = "ADD_DEMO";
export const REMOVE_DEMO = "REMOVE_DEMO";

